/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendanceregister;

import java.awt.Color;
import java.awt.Dimension;
import static java.awt.Toolkit.getDefaultToolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.read.biff.BiffException;
import jxl.write.WriteException;

/**
 *
 * @author Ashad Nadeem
 */
public class addMarks extends javax.swing.JFrame {

    /**
     * Creates new form addMarks
     */
    public addMarks() {
        try {
            
            this.height = 530;
            this.width = 385;
            initComponents();
            getStdList();
            fillTable();
            this.setVisible(true);
            this.setPreferredSize(new Dimension(this.width,this.height));
            this.setLocation(((int)getDefaultToolkit().getScreenSize().getWidth()- this.width)/2, ((int)getDefaultToolkit().getScreenSize().getHeight()- this.height)/2);
        } catch (IOException ex) {
            Logger.getLogger(addMarks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(addMarks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        NameL = new javax.swing.JLabel();
        bgL = new javax.swing.JLabel();
        marksTF = new javax.swing.JTextField();
        QNameTF = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        SubmitJB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(this.width, this.height));
        getContentPane().setLayout(null);

        jTextField1.setMinimumSize(new java.awt.Dimension(1, 2));
        jTextField1.setName(""); // NOI18N
        jTextField1.setOpaque(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(2, 2));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(64, 77, 4, 2);

        NameL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NameL.setForeground(new java.awt.Color(255, 255, 255));
        NameL.setText("Quiz Name:");
        getContentPane().add(NameL);
        NameL.setBounds(20, 90, 90, 34);

        bgL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bgL.setForeground(new java.awt.Color(255, 255, 255));
        bgL.setText("Max Marks:");
        getContentPane().add(bgL);
        bgL.setBounds(20, 130, 78, 34);

        marksTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        marksTF.setText("10");
        getContentPane().add(marksTF);
        marksTF.setBounds(120, 130, 90, 34);

        QNameTF.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        QNameTF.setForeground(Color.lightGray);
        QNameTF.setText("Quiz Name");
        QNameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                QNameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                QNameTFFocusLost(evt);
            }
        });
        QNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QNameTFActionPerformed(evt);
            }
        });
        getContentPane().add(QNameTF);
        QNameTF.setBounds(120, 90, 180, 34);

        backButton.setBackground(new java.awt.Color(255, 0, 0));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendanceregister/home-icon.png"))); // NOI18N
        backButton.setText("Back");
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(10, 440, 120, 41);

        SubmitJB.setText("Submit");
        SubmitJB.setBorderPainted(false);
        SubmitJB.setContentAreaFilled(false);
        SubmitJB.setMaximumSize(new java.awt.Dimension(91, 41));
        SubmitJB.setMinimumSize(new java.awt.Dimension(91, 41));
        SubmitJB.setPreferredSize(new java.awt.Dimension(91, 41));
        SubmitJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitJBActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitJB);
        SubmitJB.setBounds(230, 440, 110, 41);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student Name", "Marks Obtained"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setMaximumSize(new java.awt.Dimension(150, 64));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 180, 350, 230);

        jLabel1.setBackground(new java.awt.Color(255, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendanceregister/addStd.png"))); // NOI18N
        jLabel1.setPreferredSize(new Dimension(this.width, this.height));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 370, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitJBActionPerformed
        // TODO add your handling code here:
        int size = this.studentList.length + 2;
        Object [] data = new Object[size];
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            data[0] = QNameTF.getText().trim();
            data[1] = Double.parseDouble(marksTF.getText().trim());
            for(int i=0;i<studentList.length;i++){
                data[i + 2] = Double.parseDouble(model.getValueAt(i, 1).toString());
                if ((Double)data[i+2] > (Double)data[1])
                    throw new Blank("Marks Obtained cannot be greater than Maximum Marks ");
            }
            ExcelWrite write =  new ExcelWrite("Student.xls","MarkSheet",2);
            write.writeMarks(data);
            this.setVisible(false);
        } catch (IOException | NumberFormatException | BiffException | WriteException ex) {
            Logger.getLogger(updateStudentInfo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Encountered an error!");
        } catch (Blank to) {
            JOptionPane.showMessageDialog(this, to.toString());
        }
        
    }//GEN-LAST:event_SubmitJBActionPerformed

    private void QNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QNameTFActionPerformed

    private void QNameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_QNameTFFocusGained
        // TODO add your handling code here:
        if(QNameTF.getText().equals("Quiz Name")){
            QNameTF.setText("");
            QNameTF.setForeground(null);
        }
    }//GEN-LAST:event_QNameTFFocusGained

    private void QNameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_QNameTFFocusLost
        // TODO add your handling code here:
        if(QNameTF.getText().equals("")){
            QNameTF.setForeground(Color.LIGHT_GRAY);
            QNameTF.setText("Quiz Name");
        }
    }//GEN-LAST:event_QNameTFFocusLost

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        try {
            new MainGUI().setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(updateStudentInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backButtonActionPerformed
    
    public void fillTable(){
        String [] row;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for(int i=0;i<studentList.length;i++){
            row = new String[1];
            row[0] = studentList[i];
            model.addRow(row);
        }
        row = new String[1];
        row[0] = "";
        model.addRow(row);
    }
    
    
    public void getStdList() throws IOException, BiffException{
        ExcelRead read = new ExcelRead("Student.xls","Attendance");
        this.studentList = read.getStudents();
    }
    
    private int height, width;
    private String [] studentList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameL;
    private javax.swing.JTextField QNameTF;
    private javax.swing.JButton SubmitJB;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bgL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField marksTF;
    // End of variables declaration//GEN-END:variables
}
