/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendanceregister;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.awt.Color;
import java.awt.Dimension;
import static java.awt.Toolkit.getDefaultToolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.*;
import javax.swing.JOptionPane;
import jxl.read.biff.*;
import jxl.write.WriteException;

/**
 *
 * @author Ashad Nadeem
 */
public class addStudent extends javax.swing.JFrame {

    public addStudent() {
        this.height = 515;
        this.width = 375;
        gen = ' ';
        initComponents();
        this.jday.setValue(1);
        this.jMonth.setMonth(0);
        this.jYear.setYear(2000);
        this.setVisible(true);
        this.setPreferredSize(new Dimension(this.width,this.height));
        this.setLocation(((int)getDefaultToolkit().getScreenSize().getWidth()- this.width)/2, ((int)getDefaultToolkit().getScreenSize().getHeight()- this.height)/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        NameL = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        cnicL = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        ageL = new javax.swing.JLabel();
        jday = new com.toedter.components.JSpinField();
        jMonth = new com.toedter.calendar.JMonthChooser();
        jYear = new com.toedter.calendar.JYearChooser();
        bgL = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        genderL = new javax.swing.JLabel();
        maleRB = new javax.swing.JRadioButton();
        femaleRB = new javax.swing.JRadioButton();
        otherRB = new javax.swing.JRadioButton();
        AddSTDJB = new javax.swing.JButton();
        homeJB = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Student");
        setPreferredSize(new Dimension(this.width, this.height));
        getContentPane().setLayout(null);

        jTextField1.setMinimumSize(new java.awt.Dimension(1, 2));
        jTextField1.setName(""); // NOI18N
        jTextField1.setOpaque(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(2, 2));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(64, 77, 4, 2);

        NameL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NameL.setForeground(new java.awt.Color(255, 255, 255));
        NameL.setText("Name:");
        getContentPane().add(NameL);
        NameL.setBounds(10, 77, 49, 34);

        NameTF.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        NameTF.setForeground(Color.lightGray);
        NameTF.setText("Someone");
        NameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameTFFocusLost(evt);
            }
        });
        getContentPane().add(NameTF);
        NameTF.setBounds(75, 78, 180, 34);

        cnicL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cnicL.setForeground(new java.awt.Color(255, 255, 255));
        cnicL.setText("Email:");
        getContentPane().add(cnicL);
        cnicL.setBounds(10, 130, 41, 34);

        emailTF.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        emailTF.setForeground(Color.LIGHT_GRAY);
        emailTF.setText("example@domain.com");
        emailTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTFFocusLost(evt);
            }
        });
        getContentPane().add(emailTF);
        emailTF.setBounds(75, 131, 180, 34);

        ageL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ageL.setForeground(new java.awt.Color(255, 255, 255));
        ageL.setText("DOB:");
        getContentPane().add(ageL);
        ageL.setBounds(10, 183, 58, 34);
        getContentPane().add(jday);
        jday.setBounds(78, 193, 50, 20);
        getContentPane().add(jMonth);
        jMonth.setBounds(138, 193, 94, 20);
        getContentPane().add(jYear);
        jYear.setBounds(238, 193, 77, 20);

        bgL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bgL.setForeground(new java.awt.Color(255, 255, 255));
        bgL.setText("Std ID:");
        getContentPane().add(bgL);
        bgL.setBounds(10, 231, 50, 34);

        idTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(idTF);
        idTF.setBounds(78, 233, 90, 34);

        genderL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderL.setForeground(new java.awt.Color(255, 255, 255));
        genderL.setText("Gender:");
        getContentPane().add(genderL);
        genderL.setBounds(10, 283, 62, 34);

        buttonGroup1.add(maleRB);
        maleRB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        maleRB.setText("Male");
        maleRB.setOpaque(false);
        maleRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                maleRBItemStateChanged(evt);
            }
        });
        getContentPane().add(maleRB);
        maleRB.setBounds(102, 289, 60, 23);

        buttonGroup1.add(femaleRB);
        femaleRB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        femaleRB.setText("Female");
        femaleRB.setOpaque(false);
        femaleRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                femaleRBItemStateChanged(evt);
            }
        });
        getContentPane().add(femaleRB);
        femaleRB.setBounds(167, 289, 80, 23);

        buttonGroup1.add(otherRB);
        otherRB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        otherRB.setText("Other");
        otherRB.setOpaque(false);
        otherRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                otherRBItemStateChanged(evt);
            }
        });
        getContentPane().add(otherRB);
        otherRB.setBounds(248, 289, 70, 23);

        AddSTDJB.setBackground(new java.awt.Color(153, 0, 153));
        AddSTDJB.setForeground(new java.awt.Color(255, 255, 255));
        AddSTDJB.setText("Add Student");
        AddSTDJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSTDJBActionPerformed(evt);
            }
        });
        getContentPane().add(AddSTDJB);
        AddSTDJB.setBounds(90, 350, 145, 36);

        homeJB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendanceregister/home-icon.png"))); // NOI18N
        homeJB.setText("Home");
        homeJB.setBorder(null);
        homeJB.setContentAreaFilled(false);
        homeJB.setMaximumSize(new java.awt.Dimension(32, 32));
        homeJB.setMinimumSize(new java.awt.Dimension(32, 32));
        homeJB.setPreferredSize(new java.awt.Dimension(32, 32));
        homeJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJBActionPerformed(evt);
            }
        });
        getContentPane().add(homeJB);
        homeJB.setBounds(30, 430, 92, 40);

        Exit.setBackground(new java.awt.Color(255, 102, 102));
        Exit.setText("Exit");
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(240, 430, 91, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add New Student");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 30, 340, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendanceregister/addStd.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 360, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameTFFocusGained
        // TODO add your handling code here:
        if(NameTF.getText().equals("Someone")){
            NameTF.setText("");
            NameTF.setForeground(null);
        }
    }//GEN-LAST:event_NameTFFocusGained

    private void NameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameTFFocusLost
        // TODO add your handling code here:
        if(NameTF.getText().equals("")){
            NameTF.setForeground(Color.LIGHT_GRAY);
            NameTF.setText("Someone");
        }
    }//GEN-LAST:event_NameTFFocusLost

    private void emailTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTFFocusGained
        // TODO add your handling code here:
        if(emailTF.getText().equals("example@domain.com")){
            emailTF.setText("");
            emailTF.setForeground(null);
        }
    }//GEN-LAST:event_emailTFFocusGained

    private void emailTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTFFocusLost
        // TODO add your handling code here:
        if(emailTF.getText().equals("")){
            emailTF.setForeground(Color.LIGHT_GRAY);
            emailTF.setText("example@domain.com");
        }
    }//GEN-LAST:event_emailTFFocusLost

    private void maleRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_maleRBItemStateChanged
        // TODO add your handling code here:
        if(evt.getSource() == maleRB) gen = 'M';
    }//GEN-LAST:event_maleRBItemStateChanged

    private void femaleRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_femaleRBItemStateChanged
        // TODO add your handling code here:
        if(evt.getSource() == femaleRB) gen = 'F';
    }//GEN-LAST:event_femaleRBItemStateChanged

    private void otherRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_otherRBItemStateChanged
        // TODO add your handling code here:
        if(evt.getSource() == otherRB) gen = 'O';
    }//GEN-LAST:event_otherRBItemStateChanged

    private void AddSTDJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSTDJBActionPerformed
        // TODO add your handling code here:
        try{
            checking();
            String day = jday.getValue() + "";
            if (jday.getValue()<=9)
                day = "0" + day;
            String mon = jMonth.getMonth()+1 + "";
            if ((jMonth.getMonth()+1)<=9)
                mon = "0" + mon;
            String date = jYear.getYear() + "-" + mon + "-" + day;
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate localDate = LocalDate.parse(date, formatter);
            student = new Student(NameTF.getText(), emailTF.getText() , Integer.parseInt(idTF.getText()), gen, localDate);
            int save = JOptionPane.showConfirmDialog(null, "Do You Want to Save Your Details?","Save Changes",JOptionPane.YES_NO_OPTION);
            if (save == 0){
                student.addStd();
                JOptionPane.showMessageDialog(null,"Entry Added! " + student.getName(), "Saved!", JOptionPane.INFORMATION_MESSAGE);

            }
            else  {}
            fillinfo();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WriteException ex) {
            Logger.getLogger(addStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(addStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Blank ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Blank Field Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddSTDJBActionPerformed

    private void homeJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJBActionPerformed
        try {
            // TODO add your handling code here:
            MainGUI p = new MainGUI();
            this.setVisible(false);
        } catch (Exception ex) {
//            Logger.getLogger(RecordGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_homeJBActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed
    private void checking() throws Blank {
        if(NameTF.getText().trim().equals("Someone"))
            throw new Blank("Name is Required");
        if(idTF.getText().trim().equals(""))
            throw new Blank("Student ID is Required");
        if( gen == ' ') {
            throw new Blank("Please Select Gender");
        }
    }
    private void fillinfo(){
        NameTF.setForeground(null);
        emailTF.setForeground(null);
        
        NameTF.setEditable(false);
        emailTF.setEditable(false);
        idTF.setEditable(false);
        
        NameTF.setText(student.getName().trim());
        idTF.setText(""+student.getID());
        emailTF.setText(student.getEmail().trim());
//        jday.setSelectedItem(student.getDOB());
        buttonGroup1.clearSelection();
        if(student.getGender() == 'M') maleRB.setSelected(true);
        if(student.getGender() == 'F') femaleRB.setSelected(true);
        if(student.getGender() == 'O') otherRB.setSelected(true);
    }
    
    private int height,width;
    private Student student;
    private char gen;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSTDJB;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel NameL;
    private javax.swing.JTextField NameTF;
    private javax.swing.JLabel ageL;
    private javax.swing.JLabel bgL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cnicL;
    private javax.swing.JTextField emailTF;
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.JLabel genderL;
    private javax.swing.JButton homeJB;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.toedter.calendar.JMonthChooser jMonth;
    private javax.swing.JTextField jTextField1;
    private com.toedter.calendar.JYearChooser jYear;
    private com.toedter.components.JSpinField jday;
    private javax.swing.JRadioButton maleRB;
    private javax.swing.JRadioButton otherRB;
    // End of variables declaration//GEN-END:variables

    
}
