/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendanceregister;

import java.awt.Dimension;
import static java.awt.Toolkit.getDefaultToolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.read.biff.BiffException;
import jxl.write.WriteException;

/**
 *
 * @author Ashad Nadeem
 */
public class attGUI extends javax.swing.JFrame {

    /**
     * Creates new form attGUI
     */
    public attGUI(String file, String sheet) throws IOException, BiffException, WriteException {
        try{
            read = new ExcelRead("Student.xls","Attendance");
            write = new ExcelWrite("Student.xls","Attendance",0);
            this.names = read.getStudents();
            this.Tableheight = (30 + (names.length*15));
//            this.Panelheight = (int)getDefaultToolkit().getScreenSize().getHeight(); 
            this.Panelheight = (38 + this.Tableheight + 130); 
            this.setLocation(((int)getDefaultToolkit().getScreenSize().getWidth()- 320)/2, ((int)getDefaultToolkit().getScreenSize().getHeight()- this.Panelheight)/2);
//            this.setLocation(100, 200);
            this.setVisible(true);
            initComponents();
            fillTable();
        }catch(IllegalStateException e){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Heading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        presentLabel = new javax.swing.JLabel();
        homeJB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Attendance");
        setPreferredSize(new Dimension(325,this.Panelheight));

        Heading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Heading.setText("Attendance System");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Present"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setPreferredSize(new Dimension(300,this.Tableheight));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement}"), jTable1, org.jdesktop.beansbinding.BeanProperty.create("selectedElements"));
        bindingGroup.addBinding(binding);

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        presentLabel.setText(" ");

        homeJB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendanceregister/home-icon.png"))); // NOI18N
        homeJB.setText("Home");
        homeJB.setBorder(null);
        homeJB.setContentAreaFilled(false);
        homeJB.setMaximumSize(new java.awt.Dimension(32, 32));
        homeJB.setMinimumSize(new java.awt.Dimension(32, 32));
        homeJB.setPreferredSize(new java.awt.Dimension(32, 32));
        homeJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Heading))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(homeJB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(presentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Heading)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(presentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeJB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String [] att = new String[model.getRowCount()];
        for (int count = 0; count < model.getRowCount(); count++){
            if(model.getValueAt(count, 1) == null)
                att[count] = "Absent";
            else
                att[count] = "Present";
        }
        try {
            this.write.writeAttendance(att);
            JOptionPane.showMessageDialog(null,"Attendance Saved", "Thankyou!", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        } catch (IOException ex) {
            Logger.getLogger(attGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WriteException ex) {
            Logger.getLogger(attGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int present = 0;
        for (int count = 0; count < model.getRowCount(); count++){
            if(model.getValueAt(count, 1) != null)
                present++;
        }
        this.presentLabel.setText("Present: "+ present);
//        System.out.println("Present: "+ present);
    }//GEN-LAST:event_jTable1MouseClicked

    private void homeJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJBActionPerformed
        try {
            // TODO add your handling code here:
            MainGUI m = new MainGUI();
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(attGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            Logger.getLogger(attGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_homeJBActionPerformed
    
    public void fillTable(){
        String [] row;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for(int i=0;i<names.length;i++){
            row = new String[1];
            row[0] = names[i];
            model.addRow(row);
//            System.out.println(names[i]);
        }
    }
    
    private String [] names;
    private ExcelWrite write;
    private ExcelRead read;
    private int Panelheight, Tableheight;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JButton homeJB;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel presentLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
